[project]
name = "fa-chess"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "polars>=1.38.0",
    "pyarrow>=23.0.0",
    "pyside6>=6.10.2",
    "python-chess>=1.999",
]
